### ISSUE TITLE
midi 파일 parsing문제

### ISSUE THREAD

**Issue by twibeat** [twibeat/bard#1]
간단해보이는 midi파일은 읽어내는데 복잡하면 읽어내지를 못한다. Voice같은 확인 안한 클래스가 있음
music21에서 스트림이 어떻게 읽히는지 이해 필요 혹은 자체개발

**Comment by speark** [comment]
결국은 Voice로 되어 있기 때문에 최초의 Voice에 대해서 처리하는것으로 진행함
